config/routes.rb
Rails.application.routes.draw do
  get '/login', to: "sessions#new", as: "login"
  post '/sessions', to: "sessions#create", as: "sessions"
  delete '/sessions', to: "sessions#destroy"
  get 'auth/google_oauth2/callback', to: "sessions#google_omniauth_create"
  resources :likes, only: [:create]
  resources :posts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :fan_faves
  has_many :users, through: :fan_faves
end

app/models/fan_fave.rb
class FanFave < ApplicationRecord
  belongs_to :character
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user

  def self.like_or_unlike(user_id, post_id)
    like = Like.find_by(user_id: user_id, post_id: post_id)
    if like
      like.destroy
    else
      Like.create(user_id: user_id, post_id: post_id)
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes
  has_many :users, through: :likes

end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes
  has_many :posts, through: :likes
  has_secure_password



  # def password=(plaintext_password)
    # do some stuff to convert the password into a password_digest that's encrypted
  # end


  # authenticate(password)
    # Hey, does this password maatch up with this user's encrypted password in the database
  # end

  # password_confirmation=(plaintext_password)
    # does the password you just gave me match up with the other password you just gave me
  # end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :logged_in?

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @fan_fave = FanFave.new
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:name, :originating_work)
    end
end

app/controllers/fan_faves_controller.rb
class FanFavesController < ApplicationController

  def create
    @fan_fave = @user.fan_faves.create(fan_fave_params)
    redirect_to @fan_fave.character
  end

  private

  def fan_fave_params
    params.require(:fan_fave).permit(:content, :character_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    Like.like_or_unlike(current_user.id, params[:like][:post_id])
    redirect_to posts_path
  end

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @like = Like.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @like = Like.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :google_omniauth_create]

  # Render a login form
  def new
    if logged_in?
      redirect_to posts_path
    end
  end

  def google_omniauth_create
    omniauth = request.env['omniauth.auth']
      user = User.find_or_create_by(email: omniauth['info']['email']) do |u|
        u.username = omniauth['info']['email']
        u.password = SecureRandom.hex
      end
    session[:user_id] = user.id
    redirect_to posts_path
  end

  # Login and redireect
  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      flash[:errors] = ["Incorrect Username or Password"]
      redirect_to login_path
    end
  end

  # Logout
  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to posts_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/fan_faves_helper.rb
module FanFavesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :originating_work %>
    <%= form.text_field :originating_work %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Welcome <%= @user.username %>!</h3>

<h1>Characters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Originating work</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.originating_work %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Originating work:</strong>
  <%= @character.originating_work %>
</p>

<p>
  <strong>Fave this Character</strong>
  <%= form_for @fan_fave do |f| %>
    <p>Why are you faving <%= @character.name %>?</p>
    <%= f.text_area :content %>
    <%= f.hidden_field :character_id, value: @character.id %>
    <%= f.submit %>
  <% end %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/_login.html.erb
<% if logged_in? %>
<h3><%= @user.username %> | <%= link_to "Logout", sessions_path, method: :delete %> </h3>
<% else %>
<h3><%= link_to "Login", login_path %> | <%= link_to "Sign Up", new_user_path %> </h3>
<% end %>

app/views/layouts/_nav.html.erb
<% if logged_in? %>
<h3><%= @current_user.username %> | <%= link_to "Logout", sessions_path, method: :delete %> </h3>
<% else %>
<h3>You are not logged in! <%= link_to "Login", login_path %> or <%= link_to "Sign Up", new_user_path %></h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthInRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:errors] %>
    <ul style="color: red;">
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
    <% end%>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome to TheDenied.com, <%= @current_user.username %>!</h1>

<div class="cards">
<% @posts.each do |post|%>
  <div class="card">
    <p><%= post.content %></p>
    <%= form_for @like do |f| %>
      <%=f.hidden_field :post_id, value: post.id %>
      <%=f.submit "👍  #{post.likes.size}"%>
    <% end %>
  </div>

<% end %>
</div>


<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p><strong>Likes: <%= @post.likes.size %></strong></p>

<%= form_for @like do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.submit "Like this Post" %>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit %>
  <%# f.label :username %>
  <%# f.text_field :username %><br>
<% end %>